import type { StorybookConfig } from '@storybook/web-components-vite';

// Storybook 10 + @storybook/web-components-vite builder (spec § 6.F.1).
//
// addons: @storybook/addon-essentials is intentionally absent — it was
// discontinued at the Storybook 9 → 10 transition (no ^10.x is published) and
// removed from the dependency table by AM-001/AM-016. Autodocs ships in
// Storybook 10 core and needs no addon entry.
const config: StorybookConfig = {
  framework: { name: '@storybook/web-components-vite', options: {} },
  stories: ['../stories/**/*.@(mdx|stories.@(ts|js))'],
  addons: [
    '@storybook/addon-a11y',
    '@storybook/addon-themes', // toolbar switcher for data-accent / data-gray previews
  ],
  staticDirs: ['../public'],
  // Autodocs is generated by default for any story tagged 'autodocs' in
  // Storybook 10 — the SB8-era `docs: { autodocs: 'tag' }` toggle was removed
  // from DocsOptions, so no docs config entry is required here.
  viteFinal: async (cfg) => {
    // CEM consumed automatically when customElements.json is present at the project root.
    return cfg;
  },
};

export default config;
